apiVersion: apps/v1
kind: Deployment
metadata:
  name: ciss-fescaro-solution
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ciss-fescaro-solution
  template:
    metadata:
      labels:
        app: ciss-fescaro-solution
    spec:
      containers:
      - name: ciss-fescaro-solution
        image: ciss-fescaro-solution:latest
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_REDIS_HOST
          value: redis
        - name: SPRING_REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: ciss-fescaro-solution
spec:
  selector:
    app: ciss-fescaro-solution
  ports:
  - port: 8082
    targetPort: 8082